nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

# npmScopes:
#   urizafrir:
#     npmRegistryServer: "https://npm.pkg.github.com"
#     npmAlwaysAuth: true
  
# npmRegistries:
#   "https://npm.pkg.github.com":
#     npmAuthToken: "${GITHUB_TOKEN}"